### ISSUE TITLE
gosweep should skip vendor folder

### ISSUE THREAD

**Issue by drewwells** [hailiang/goclean#1]
Looking at ./... catches all packages including those in the vendor folder. This can cause issues if vendored code isn't held to same linting standards as primary package.

**Comment by h12w** [comment]
Any suggestions on implementing this behaviour in bash?

IMHO, I do not think it is a serious issue,  because a library normally should not force vendoring but relies on the master branch of other packages, and vendoring should only be done across an organization.

I have explained the convensions here:
https://groups.google.com/d/msg/golang-nuts/NbThPX_b680/TjVFC0BNAwAJ

**Comment by drewwells** [comment]
As for the bash workaround, depends on how gosweep works.

This works for go vet:

`go vet $(go list -f '{{.ImportPath}}' ./... | grep -v /vendor/)`

It creates a set of import paths ie. `github.com/user/repoa github.com/user/repob`

**Comment by steenzout** [comment]
check #2 for a patch.

**Comment by h12w** [comment]
Merged, thanks!
